// Code generated by protoc-gen-go. DO NOT EDIT.
// source: TransportProtocal.proto

package protocol

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type MSG int32

const (
	MSG_Unknown_MSG              MSG = 0
	MSG_Login_Request            MSG = 4097
	MSG_Login_Response           MSG = 4098
	MSG_Device_Register_Request  MSG = 8193
	MSG_Device_Register_Response MSG = 8194
)

var MSG_name = map[int32]string{
	0:    "Unknown_MSG",
	4097: "Login_Request",
	4098: "Login_Response",
	8193: "Device_Register_Request",
	8194: "Device_Register_Response",
}

var MSG_value = map[string]int32{
	"Unknown_MSG":              0,
	"Login_Request":            4097,
	"Login_Response":           4098,
	"Device_Register_Request":  8193,
	"Device_Register_Response": 8194,
}

func (x MSG) String() string {
	return proto.EnumName(MSG_name, int32(x))
}

func (MSG) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_14daefcd353aa445, []int{0}
}

//用户端登陆请求
type LoginRequest struct {
	//用户登录账号
	Username string `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	//用户登录密码
	Password             string      `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	Ip                   *NetAddress `protobuf:"bytes,3,opt,name=ip,proto3" json:"ip,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *LoginRequest) Reset()         { *m = LoginRequest{} }
func (m *LoginRequest) String() string { return proto.CompactTextString(m) }
func (*LoginRequest) ProtoMessage()    {}
func (*LoginRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_14daefcd353aa445, []int{0}
}

func (m *LoginRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginRequest.Unmarshal(m, b)
}
func (m *LoginRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginRequest.Marshal(b, m, deterministic)
}
func (m *LoginRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginRequest.Merge(m, src)
}
func (m *LoginRequest) XXX_Size() int {
	return xxx_messageInfo_LoginRequest.Size(m)
}
func (m *LoginRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginRequest.DiscardUnknown(m)
}

var xxx_messageInfo_LoginRequest proto.InternalMessageInfo

func (m *LoginRequest) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *LoginRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *LoginRequest) GetIp() *NetAddress {
	if m != nil {
		return m.Ip
	}
	return nil
}

//用户端登陆回应
type LoginResponse struct {
	Ack bool `protobuf:"varint,1,opt,name=ack,proto3" json:"ack,omitempty"`
	//客户端节点
	Client               *Client  `protobuf:"bytes,2,opt,name=client,proto3" json:"client,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginResponse) Reset()         { *m = LoginResponse{} }
func (m *LoginResponse) String() string { return proto.CompactTextString(m) }
func (*LoginResponse) ProtoMessage()    {}
func (*LoginResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_14daefcd353aa445, []int{1}
}

func (m *LoginResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginResponse.Unmarshal(m, b)
}
func (m *LoginResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginResponse.Marshal(b, m, deterministic)
}
func (m *LoginResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginResponse.Merge(m, src)
}
func (m *LoginResponse) XXX_Size() int {
	return xxx_messageInfo_LoginResponse.Size(m)
}
func (m *LoginResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginResponse.DiscardUnknown(m)
}

var xxx_messageInfo_LoginResponse proto.InternalMessageInfo

func (m *LoginResponse) GetAck() bool {
	if m != nil {
		return m.Ack
	}
	return false
}

func (m *LoginResponse) GetClient() *Client {
	if m != nil {
		return m.Client
	}
	return nil
}

//设备上线请求
type DeviceRegisterRequest struct {
	Device               *Device  `protobuf:"bytes,1,opt,name=device,proto3" json:"device,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeviceRegisterRequest) Reset()         { *m = DeviceRegisterRequest{} }
func (m *DeviceRegisterRequest) String() string { return proto.CompactTextString(m) }
func (*DeviceRegisterRequest) ProtoMessage()    {}
func (*DeviceRegisterRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_14daefcd353aa445, []int{2}
}

func (m *DeviceRegisterRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeviceRegisterRequest.Unmarshal(m, b)
}
func (m *DeviceRegisterRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeviceRegisterRequest.Marshal(b, m, deterministic)
}
func (m *DeviceRegisterRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeviceRegisterRequest.Merge(m, src)
}
func (m *DeviceRegisterRequest) XXX_Size() int {
	return xxx_messageInfo_DeviceRegisterRequest.Size(m)
}
func (m *DeviceRegisterRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeviceRegisterRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeviceRegisterRequest proto.InternalMessageInfo

func (m *DeviceRegisterRequest) GetDevice() *Device {
	if m != nil {
		return m.Device
	}
	return nil
}

//设备上线回应
type DeviceRegisterResponse struct {
	//请求是否成功
	Ack bool `protobuf:"varint,1,opt,name=ack,proto3" json:"ack,omitempty"`
	//返回外网IP地址
	Address              *NetAddress `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *DeviceRegisterResponse) Reset()         { *m = DeviceRegisterResponse{} }
func (m *DeviceRegisterResponse) String() string { return proto.CompactTextString(m) }
func (*DeviceRegisterResponse) ProtoMessage()    {}
func (*DeviceRegisterResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_14daefcd353aa445, []int{3}
}

func (m *DeviceRegisterResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeviceRegisterResponse.Unmarshal(m, b)
}
func (m *DeviceRegisterResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeviceRegisterResponse.Marshal(b, m, deterministic)
}
func (m *DeviceRegisterResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeviceRegisterResponse.Merge(m, src)
}
func (m *DeviceRegisterResponse) XXX_Size() int {
	return xxx_messageInfo_DeviceRegisterResponse.Size(m)
}
func (m *DeviceRegisterResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeviceRegisterResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeviceRegisterResponse proto.InternalMessageInfo

func (m *DeviceRegisterResponse) GetAck() bool {
	if m != nil {
		return m.Ack
	}
	return false
}

func (m *DeviceRegisterResponse) GetAddress() *NetAddress {
	if m != nil {
		return m.Address
	}
	return nil
}

//封装Request
type Request struct {
	LoginRequest          *LoginRequest          `protobuf:"bytes,1,opt,name=loginRequest,proto3" json:"loginRequest,omitempty"`
	DeviceRegisterRequest *DeviceRegisterRequest `protobuf:"bytes,2,opt,name=deviceRegisterRequest,proto3" json:"deviceRegisterRequest,omitempty"`
	XXX_NoUnkeyedLiteral  struct{}               `json:"-"`
	XXX_unrecognized      []byte                 `json:"-"`
	XXX_sizecache         int32                  `json:"-"`
}

func (m *Request) Reset()         { *m = Request{} }
func (m *Request) String() string { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()    {}
func (*Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_14daefcd353aa445, []int{4}
}

func (m *Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Request.Unmarshal(m, b)
}
func (m *Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Request.Marshal(b, m, deterministic)
}
func (m *Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Request.Merge(m, src)
}
func (m *Request) XXX_Size() int {
	return xxx_messageInfo_Request.Size(m)
}
func (m *Request) XXX_DiscardUnknown() {
	xxx_messageInfo_Request.DiscardUnknown(m)
}

var xxx_messageInfo_Request proto.InternalMessageInfo

func (m *Request) GetLoginRequest() *LoginRequest {
	if m != nil {
		return m.LoginRequest
	}
	return nil
}

func (m *Request) GetDeviceRegisterRequest() *DeviceRegisterRequest {
	if m != nil {
		return m.DeviceRegisterRequest
	}
	return nil
}

//封装Response
type Response struct {
	LoginResponse          *LoginResponse          `protobuf:"bytes,1,opt,name=loginResponse,proto3" json:"loginResponse,omitempty"`
	DeviceRegisterResponse *DeviceRegisterResponse `protobuf:"bytes,2,opt,name=deviceRegisterResponse,proto3" json:"deviceRegisterResponse,omitempty"`
	XXX_NoUnkeyedLiteral   struct{}                `json:"-"`
	XXX_unrecognized       []byte                  `json:"-"`
	XXX_sizecache          int32                   `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_14daefcd353aa445, []int{5}
}

func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (m *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(m, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetLoginResponse() *LoginResponse {
	if m != nil {
		return m.LoginResponse
	}
	return nil
}

func (m *Response) GetDeviceRegisterResponse() *DeviceRegisterResponse {
	if m != nil {
		return m.DeviceRegisterResponse
	}
	return nil
}

//封装Command 暂时不用 点对点传输需要Command
type Command struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Command) Reset()         { *m = Command{} }
func (m *Command) String() string { return proto.CompactTextString(m) }
func (*Command) ProtoMessage()    {}
func (*Command) Descriptor() ([]byte, []int) {
	return fileDescriptor_14daefcd353aa445, []int{6}
}

func (m *Command) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Command.Unmarshal(m, b)
}
func (m *Command) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Command.Marshal(b, m, deterministic)
}
func (m *Command) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Command.Merge(m, src)
}
func (m *Command) XXX_Size() int {
	return xxx_messageInfo_Command.Size(m)
}
func (m *Command) XXX_DiscardUnknown() {
	xxx_messageInfo_Command.DiscardUnknown(m)
}

var xxx_messageInfo_Command proto.InternalMessageInfo

//封装Notification
type Notification struct {
	Id                   uint32   `protobuf:"fixed32,1,opt,name=id,proto3" json:"id,omitempty"`
	Msg                  string   `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Notification) Reset()         { *m = Notification{} }
func (m *Notification) String() string { return proto.CompactTextString(m) }
func (*Notification) ProtoMessage()    {}
func (*Notification) Descriptor() ([]byte, []int) {
	return fileDescriptor_14daefcd353aa445, []int{7}
}

func (m *Notification) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Notification.Unmarshal(m, b)
}
func (m *Notification) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Notification.Marshal(b, m, deterministic)
}
func (m *Notification) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Notification.Merge(m, src)
}
func (m *Notification) XXX_Size() int {
	return xxx_messageInfo_Notification.Size(m)
}
func (m *Notification) XXX_DiscardUnknown() {
	xxx_messageInfo_Notification.DiscardUnknown(m)
}

var xxx_messageInfo_Notification proto.InternalMessageInfo

func (m *Notification) GetId() uint32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Notification) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

//封装顶层Message
type Message struct {
	MsgType              MSG           `protobuf:"varint,1,opt,name=msg_type,json=msgType,proto3,enum=protocol.MSG" json:"msg_type,omitempty"`
	Sequence             uint32        `protobuf:"fixed32,2,opt,name=sequence,proto3" json:"sequence,omitempty"`
	SessionId            uint32        `protobuf:"fixed32,3,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Request              *Request      `protobuf:"bytes,4,opt,name=request,proto3" json:"request,omitempty"`
	Response             *Response     `protobuf:"bytes,5,opt,name=Response,proto3" json:"Response,omitempty"`
	Notification         *Notification `protobuf:"bytes,6,opt,name=notification,proto3" json:"notification,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *Message) Reset()         { *m = Message{} }
func (m *Message) String() string { return proto.CompactTextString(m) }
func (*Message) ProtoMessage()    {}
func (*Message) Descriptor() ([]byte, []int) {
	return fileDescriptor_14daefcd353aa445, []int{8}
}

func (m *Message) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Message.Unmarshal(m, b)
}
func (m *Message) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Message.Marshal(b, m, deterministic)
}
func (m *Message) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Message.Merge(m, src)
}
func (m *Message) XXX_Size() int {
	return xxx_messageInfo_Message.Size(m)
}
func (m *Message) XXX_DiscardUnknown() {
	xxx_messageInfo_Message.DiscardUnknown(m)
}

var xxx_messageInfo_Message proto.InternalMessageInfo

func (m *Message) GetMsgType() MSG {
	if m != nil {
		return m.MsgType
	}
	return MSG_Unknown_MSG
}

func (m *Message) GetSequence() uint32 {
	if m != nil {
		return m.Sequence
	}
	return 0
}

func (m *Message) GetSessionId() uint32 {
	if m != nil {
		return m.SessionId
	}
	return 0
}

func (m *Message) GetRequest() *Request {
	if m != nil {
		return m.Request
	}
	return nil
}

func (m *Message) GetResponse() *Response {
	if m != nil {
		return m.Response
	}
	return nil
}

func (m *Message) GetNotification() *Notification {
	if m != nil {
		return m.Notification
	}
	return nil
}

func init() {
	proto.RegisterEnum("protocol.MSG", MSG_name, MSG_value)
	proto.RegisterType((*LoginRequest)(nil), "protocol.LoginRequest")
	proto.RegisterType((*LoginResponse)(nil), "protocol.LoginResponse")
	proto.RegisterType((*DeviceRegisterRequest)(nil), "protocol.DeviceRegisterRequest")
	proto.RegisterType((*DeviceRegisterResponse)(nil), "protocol.DeviceRegisterResponse")
	proto.RegisterType((*Request)(nil), "protocol.Request")
	proto.RegisterType((*Response)(nil), "protocol.Response")
	proto.RegisterType((*Command)(nil), "protocol.Command")
	proto.RegisterType((*Notification)(nil), "protocol.Notification")
	proto.RegisterType((*Message)(nil), "protocol.Message")
}

func init() { proto.RegisterFile("TransportProtocal.proto", fileDescriptor_14daefcd353aa445) }

var fileDescriptor_14daefcd353aa445 = []byte{
	// 540 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x53, 0xdf, 0x6b, 0xd3, 0x50,
	0x14, 0xb6, 0x99, 0x36, 0xed, 0xe9, 0x0f, 0xeb, 0x91, 0xb5, 0x61, 0x3a, 0x5a, 0x02, 0x42, 0x51,
	0x08, 0x52, 0x5f, 0x64, 0x20, 0xcc, 0x4d, 0x28, 0x82, 0x1d, 0xf3, 0x76, 0x03, 0xdf, 0x4a, 0xcc,
	0xbd, 0x86, 0xcb, 0x92, 0x7b, 0x63, 0x6e, 0xe6, 0x18, 0xf8, 0xa2, 0x2f, 0xfe, 0x13, 0xbe, 0xf9,
	0x8f, 0x4a, 0x6e, 0x6e, 0x9a, 0x74, 0x6b, 0x9f, 0x72, 0xcf, 0xef, 0xef, 0xfb, 0xce, 0x09, 0x8c,
	0x2e, 0x52, 0x5f, 0xa8, 0x44, 0xa6, 0xd9, 0x79, 0x2a, 0x33, 0x19, 0xf8, 0x91, 0x97, 0xe4, 0x0f,
	0x6c, 0xe9, 0x4f, 0x20, 0xa3, 0x03, 0x3c, 0x61, 0xbe, 0x38, 0x37, 0x56, 0x11, 0x75, 0x03, 0xe8,
	0x7e, 0x92, 0x21, 0x17, 0x84, 0x7d, 0xbf, 0x66, 0x2a, 0xc3, 0x03, 0x68, 0x5d, 0x2b, 0x96, 0x0a,
	0x3f, 0x66, 0x4e, 0x63, 0xd2, 0x98, 0xb6, 0xc9, 0xda, 0xce, 0x63, 0x89, 0xaf, 0xd4, 0x8d, 0x4c,
	0xa9, 0x63, 0x15, 0xb1, 0xd2, 0xc6, 0x67, 0x60, 0xf1, 0xc4, 0xd9, 0x9b, 0x34, 0xa6, 0x9d, 0x59,
	0xc7, 0x3b, 0x63, 0xd9, 0x7b, 0x4a, 0x53, 0xa6, 0x14, 0xb1, 0x78, 0xe2, 0x9e, 0x40, 0xcf, 0x0c,
	0x51, 0x89, 0x14, 0x8a, 0xe1, 0x00, 0xf6, 0xfc, 0xe0, 0x4a, 0x0f, 0x68, 0x91, 0xfc, 0x89, 0x63,
	0x68, 0x06, 0x11, 0x67, 0x22, 0xd3, 0x9d, 0x3b, 0x33, 0xdb, 0x3b, 0xd5, 0x26, 0x31, 0x6e, 0xf7,
	0x2d, 0xec, 0x7f, 0x60, 0x3f, 0x78, 0xc0, 0x08, 0x0b, 0xb9, 0xca, 0x58, 0x5a, 0x22, 0x1e, 0x43,
	0x93, 0xea, 0x80, 0x6e, 0x97, 0x57, 0x9a, 0x3c, 0xe3, 0x76, 0x3f, 0xc3, 0xf0, 0x6e, 0xe5, 0x4e,
	0x18, 0x2f, 0xc0, 0xf6, 0x0b, 0xe0, 0x06, 0xc7, 0x06, 0x97, 0x32, 0xe6, 0xfe, 0x6d, 0x80, 0x5d,
	0xce, 0x3f, 0x82, 0x6e, 0x54, 0x53, 0xd0, 0xa0, 0x18, 0x7a, 0xa5, 0xec, 0x5e, 0x5d, 0x5f, 0xb2,
	0x91, 0x8b, 0x97, 0xb0, 0x4f, 0xb7, 0x91, 0x32, 0xc3, 0xc7, 0x55, 0x93, 0xad, 0xdc, 0xc9, 0xf6,
	0x6a, 0xf7, 0x5f, 0x03, 0x5a, 0x6b, 0x92, 0xef, 0xa0, 0x17, 0xd5, 0xc5, 0x37, 0x00, 0x47, 0xf7,
	0x00, 0x16, 0x61, 0xb2, 0x99, 0x8d, 0x5f, 0x60, 0x48, 0xb7, 0xaa, 0x67, 0x30, 0x4e, 0x76, 0x63,
	0x34, 0x0d, 0x77, 0xd4, 0xbb, 0x6d, 0xb0, 0x4f, 0x65, 0x1c, 0xfb, 0x82, 0xba, 0xaf, 0xa1, 0x7b,
	0x26, 0x33, 0xfe, 0x8d, 0x07, 0x7e, 0xc6, 0xa5, 0xc0, 0x3e, 0x58, 0x9c, 0x6a, 0xa0, 0x36, 0xb1,
	0x38, 0xcd, 0x17, 0x15, 0xab, 0xd0, 0x1c, 0x5d, 0xfe, 0x74, 0xff, 0x58, 0x60, 0x2f, 0x98, 0x52,
	0x7e, 0xc8, 0x70, 0x0a, 0xad, 0x58, 0x85, 0xab, 0xec, 0x36, 0x29, 0xc8, 0xf5, 0x67, 0xbd, 0x0a,
	0xd4, 0x62, 0x39, 0x27, 0x76, 0xac, 0xc2, 0x8b, 0xdb, 0x44, 0x5f, 0xb0, 0xca, 0x35, 0x12, 0x41,
	0x01, 0xdf, 0x26, 0x6b, 0x1b, 0x0f, 0x01, 0x14, 0x53, 0x8a, 0x4b, 0xb1, 0xe2, 0x54, 0x5f, 0xb2,
	0x4d, 0xda, 0xc6, 0xf3, 0x91, 0xe2, 0x2b, 0xb0, 0x53, 0xb3, 0x9c, 0x87, 0x9a, 0xf8, 0x93, 0x6a,
	0x46, 0xb9, 0x8e, 0x32, 0x03, 0xbd, 0x4a, 0x7f, 0xe7, 0x91, 0xce, 0xc6, 0x7a, 0xb6, 0x11, 0xa6,
	0xda, 0xd1, 0x11, 0x74, 0x45, 0x8d, 0xbf, 0xd3, 0xbc, 0x7b, 0x43, 0x75, 0x75, 0xc8, 0x46, 0xee,
	0xcb, 0x9f, 0xb0, 0xb7, 0x58, 0xce, 0xf1, 0x31, 0x74, 0x2e, 0xc5, 0x95, 0x90, 0x37, 0x62, 0xb5,
	0x58, 0xce, 0x07, 0x0f, 0x10, 0xcd, 0x4f, 0xb7, 0x32, 0xe8, 0x06, 0xbf, 0x26, 0xf8, 0x14, 0xfa,
	0xa5, 0xaf, 0x98, 0x3c, 0xf8, 0x3d, 0xc1, 0xe7, 0x30, 0x2a, 0x36, 0xb7, 0x2a, 0x57, 0x54, 0x95,
	0x1c, 0xe3, 0x21, 0x38, 0xf7, 0xa3, 0x65, 0xf1, 0xf1, 0xd7, 0xa6, 0x86, 0xf8, 0xe6, 0x7f, 0x00,
	0x00, 0x00, 0xff, 0xff, 0x1f, 0x65, 0x21, 0xc6, 0x7f, 0x04, 0x00, 0x00,
}
